name: DELETER 29-32
on:
  schedule:
    - cron: 1 * */30 * *
  workflow_dispatch:
jobs:
  ProsesBackup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Menginstall Rclone
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Memuat konfigurasi Rclone
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.ssh }}
        EOF
    - name: DELETE 29
      run: |
         rclone delete "ssh29:" --drive-use-trash=false
    - name: DELETE 30
      run: |
         rclone delete "ssh30:" --drive-use-trash=false
    - name: DELETE 31
      run: |
         rclone delete "ssh31:" --drive-use-trash=false
    - name: DELETE 32
      run: |
         rclone delete "ssh32:" --drive-use-trash=false
